const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || "https://db.sinjaikab.go.id/wisata/api";

export const API_ENDPOINTS = {
	LOKASI: `${API_BASE_URL}/lokasi`,
	LOKASI_DETAIL: (id: number) => `${API_BASE_URL}/lokasi/${id}`,
	LOKASI_UPDATE: (id: number) => `${API_BASE_URL}/lokasi/${id}`,
	LOKASI_DELETE: (id: number) => `${API_BASE_URL}/lokasi/${id}`,
	CHECKIN: `${API_BASE_URL}/checkin`,
	UPLOAD: `${API_BASE_URL}/upload`,
	USER_HISTORY: (suiAddress: string) => `${API_BASE_URL}/user/${suiAddress}/riwayat`,
	USER_ACTIVITY: (suiAddress: string) => `${API_BASE_URL}/user/${suiAddress}/activity`,
	ADMIN_USER_ACTIVITY: (email: string) => `${API_BASE_URL}/admin/user-activity/${email}`,
	USER_REGISTER: `${API_BASE_URL}/user`,
	LOGOUT: `${API_BASE_URL}/auth/logout`,
	AUTH_SALT: `${API_BASE_URL}/auth/salt`,
	LEADERBOARD: `${API_BASE_URL}/leaderboard`,
	LOKASI_LIKE: (id: number) => `${API_BASE_URL}/lokasi/${id}/like`,
	LOKASI_COMMENT: (id: number) => `${API_BASE_URL}/lokasi/${id}/comment`,
	CHECKIN_LIKE: (id: number) => `${API_BASE_URL}/checkin/${id}/like`,
	COMMENT_HIDE: (id: number) => `${API_BASE_URL}/comment/${id}/hide`,
	CHECKIN_HIDE: (id: number) => `${API_BASE_URL}/checkin/${id}/hide`,
	NOTIFICATIONS: `${API_BASE_URL}/notifications`,
	NOTIFICATIONS_ARCHIVE: `${API_BASE_URL}/notifications/archive`,
	LOKASI_CLAIM: (id: number) => `${API_BASE_URL}/lokasi/${id}/claim`,
	LOKASI_UNCLAIM: (id: number) => `${API_BASE_URL}/lokasi/${id}/unclaim`,
	ADMIN_CLAIMS: `${API_BASE_URL}/admin/claims`,
	ADMIN_CLAIM_UPDATE: (id: number) => `${API_BASE_URL}/admin/claims/${id}`,
	SPONSOR: `${API_BASE_URL}/sponsor`,
};
